// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO7CVdYdrjRG_NqICaPlk3PVIWlcPBqWw',
    appId: '1:435400540716:web:672cc9380cdb5d37854789',
    messagingSenderId: '435400540716',
    projectId: 'takeit-today',
    authDomain: 'takeit-today.firebaseapp.com',
    storageBucket: 'takeit-today.appspot.com',
    measurementId: 'G-5M42XFC7G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbwO-uNaJWYkabI6fZIM700Dm6jC7xUJE',
    appId: '1:435400540716:android:f8a8c390cbb18984854789',
    messagingSenderId: '435400540716',
    projectId: 'takeit-today',
    storageBucket: 'takeit-today.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjvqLIdFoBmiID0u4YVT8o4P5jPtCSN_c',
    appId: '1:435400540716:ios:952dfe3c6c8e2f0c854789',
    messagingSenderId: '435400540716',
    projectId: 'takeit-today',
    storageBucket: 'takeit-today.appspot.com',
    iosBundleId: 'com.example.takeit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjvqLIdFoBmiID0u4YVT8o4P5jPtCSN_c',
    appId: '1:435400540716:ios:952dfe3c6c8e2f0c854789',
    messagingSenderId: '435400540716',
    projectId: 'takeit-today',
    storageBucket: 'takeit-today.appspot.com',
    iosBundleId: 'com.example.takeit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO7CVdYdrjRG_NqICaPlk3PVIWlcPBqWw',
    appId: '1:435400540716:web:2fc0a647fb4cf235854789',
    messagingSenderId: '435400540716',
    projectId: 'takeit-today',
    authDomain: 'takeit-today.firebaseapp.com',
    storageBucket: 'takeit-today.appspot.com',
    measurementId: 'G-T9DG2VV3W1',
  );
}
